farketmez-app/farketmez-backend

farketmez/farketmez_db/farketmez_db_script/farketmez_db_01.sql, farketmez/src/main/java/com/mmhb/farketmez/controller/SettingsController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/SettingsDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/SettingsMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Settings.java, farketmez/src/main/java/com/mmhb/farketmez/repository/SettingsRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/SettingsService.java
Veri tabanında ayarlar tablosu ve buna bağlı işlemler eklenmeliydi
Veri tabanına ayarlar tablosu eklendi
Ayarlarla ilgili yapılar paketlere eklendi
=> ayarlar tablosu ve temel yapı oluşturuldu

farketmez/pom.xml, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/EventTypeController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/InterestController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/LocationController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/ParticipantController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserInterestController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserTypeController.java, farketmez/src/main/java/com/mmhb/farketmez/model/Participant.java, farketmez/src/main/java/com/mmhb/farketmez/model/User.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventTypeService.java, farketmez/src/main/java/com/mmhb/farketmez/service/InterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/LocationService.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserInterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserTypeService.java
mapper ve dtolara göre servis ve controller metodlarının güncellenmesi gerekliydi
mapper ve dtolarla servis metodları güncellenerek bu güncllemeler controllera taşındı.
=> mapper ve dtoya göre servis ve controllerlar güncllendi

farketmez/pom.xml, farketmez/src/test/java/com/mmhb/farketmez/controller/UserControllerTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/EventTypeServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/InterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/LocationServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/SettingsServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserInterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserTypeServiceTest.java
Servislerin test edilmesi gerekliydi.
Her class için test classları yazılarak servisler test edildi.
=> Servisler için test classları oluşturuldu

farketmez/pom.xml, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/InterestController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/LocationController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/ParticipantController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/SettingsController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserInterestController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserTypeController.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/UserInterestMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/UserInterest.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/java/com/mmhb/farketmez/service/InterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/LocationService.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/main/java/com/mmhb/farketmez/service/SettingsService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserInterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserTypeService.java, farketmez/src/main/resources/application.properties, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/InterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/LocationServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/SettingsServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserInterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserTypeServiceTest.java
Serviste gereksiz kullanılan dto ve mapper kaldırılmalıydı.
Servis paketlerinde bulunan dto ve mapper dosyaları kaldırıldı buna bağlı olarka controller ve servis testleri güncellendi.
=> gereksiz dto ve mapper kullanımı servisten kaldırıldı

farketmez/src/main/java/com/mmhb/farketmez/controller/UserInterestController.java, farketmez/src/main/java/com/mmhb/farketmez/repository/UserInterestRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserInterestService.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserInterestServiceTest.java
Kullanıcılara göre interest bilgilerinin listelenmesi gerekiyordu
Repositoryde oluşturulan queryler yardımıyla user ve interest bilgileri bağlandı, ardından servis ve controller kısımlarında işlendi.
=> Kullanıcıların interest bilgileri listelendi

farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/ParticipantDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/ParticipantMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Event.java, farketmez/src/main/java/com/mmhb/farketmez/model/Participant.java, farketmez/src/main/java/com/mmhb/farketmez/repository/ParticipantRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
Kullanıcının katıldığı etkinlikler listelenmeli
Participant, user ve event arasında kurulan ilişkiye göre repositoryde sorgu yazılarak kullanıcın katıldığı etkinlikler listelendi
=> Kullanıcının katıldığı etkinlikler listelendi

farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserServiceTest.java
Create ve update methodlarında şifre haslenmiyordu.
User servisteki create ve update methodlarında şifreler haslenerek saklandı.
=> User serviste şifreler haslenerek kaydedildi

farketmez/src/main/java/com/mmhb/farketmez/controller/ParticipantController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/RateRequest.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/EventMapper.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/ParticipantMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Participant.java, farketmez/src/main/java/com/mmhb/farketmez/repository/ParticipantRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
Kullanıcın katıldığı etkinlikleri puanlayabilmesi ve verdiği puanı değiştirebilme özelliği eklenmeliydi.
RateRequest dto oluşturuldu.
Participant serviste RateRequest kullanılarak kullanıcının etkinliği puanlayabilmesi sağlandı.
Puanlama özelliğine edit özellik eklenerek puan düzenleyebilme sağlandı.
Etkinliğin oylanabilmesi için etkinliğin geçiş olması şartı eklendi.
Test methodları yazılarak servisin doğruluğu kanıtlandı.
=> Katılınan etkinlik için puanlama oluşturma ve değiştirebilme eklendi

farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java
Uygulamaya giriş yapılamıyordu.
giriş için kullanılan mail ve password compare edilerek giriş sağlandı.
=> Giriş kontrolü düzeltildi

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/repository/EventRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/resources/application.properties
- Nearme renamed to near-events.
- Moved to event controller.
- Request params are latitude and longitude
Example : http://localhost:8080/events/near-events?lat=39.748366&long=30.499565
=> Near events fixed.

farketmez/farketmez_db/farketmez_db_script/farketmez_db_01.sql, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/EventDTO.java, farketmez/src/main/java/com/mmhb/farketmez/dto/LocationDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/EventMapper.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/LocationMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Event.java, farketmez/src/main/java/com/mmhb/farketmez/model/Location.java, farketmez/src/main/java/com/mmhb/farketmez/repository/EventRepository.java, farketmez/src/main/java/com/mmhb/farketmez/repository/ParticipantRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
- Tables have been updated. Sql scripts should be used.
- Tests are missing. (Done)
- There was a bug in the section "/{userId}/all". It has been fixed.
=> Bugs are fixed. Public events is ready to use. Tests are missing.

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java
- There was a bug on user events that returns all events, its is fixed now.
- To resolve conflict in Spring MVC, user events request URL has been modified like "events/user-events?user-id=1"
- There was an error on public events. Its fixed now.
=> Request body of user events done.

farketmez/pom.xml, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/InterestDTO.java, farketmez/src/main/java/com/mmhb/farketmez/exception/CustomOperationException.java, farketmez/src/main/java/com/mmhb/farketmez/exception/DatabaseOperationException.java, farketmez/src/main/java/com/mmhb/farketmez/exception/OperationNotAllowedException.java, farketmez/src/main/java/com/mmhb/farketmez/exception/ServiceException.java, farketmez/src/main/java/com/mmhb/farketmez/exception/UserInputException.java, farketmez/src/main/java/com/mmhb/farketmez/exception/UserNotAuthorizedException.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/InterestMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Interest.java, farketmez/src/main/java/com/mmhb/farketmez/model/UserInterest.java, farketmez/src/main/java/com/mmhb/farketmez/security/SecurityConfig.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventTypeService.java, farketmez/src/main/java/com/mmhb/farketmez/service/InterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/LocationService.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/main/java/com/mmhb/farketmez/service/SettingsService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserInterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java, farketmez/src/main/java/com/mmhb/farketmez/type/InterestType.java, farketmez/src/main/resources/application-dev.properties, farketmez/src/main/resources/application.properties, farketmez/src/test/java/com/mmhb/farketmez/service/InterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserInterestServiceTest.java
cors hatası çözülmeli.
excepitonların sebebi anlaşılmıyor.
interest bilgileri eklenmeliydi.
IllegalArgumentException gibi exceptionlar yerine exception paketlerinin altında uygulamaya özel exceptionlar oluşturulup servis methodlarına eklendi
cors hatasına sebep olan frontend ile backendin farklı port numarası ignore edilerek application-dev.properties oluşturuldu.
ineterst bilgileri type olarak tanımlanıp test methodlarında da bu şekilde kontrol edildi.
=> Corse hatası çözüldü ve excepitonlar için classlar yazıldı

farketmez/src/main/java/com/mmhb/farketmez/dto/UserTypeDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/UserTypeMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/UserType.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserTypeService.java, farketmez/src/main/java/com/mmhb/farketmez/type/UserTypeEnum.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserTypeServiceTest.java
Usertype için type belirlenerek kullancı tipleri sınıflandırılabilmeliydi.
Usertype için UsertypeEnum clası type paketinde oluşturularak kullanıcı tipleri burada 3 kategoriye ayrıldı.
Not: Usertype adınının type paketinde kullanılmamasının sebebi modeldeki isimle aynı olmasıdır.
=> Updated usertype

farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java, farketmez/src/main/java/com/mmhb/farketmez/controller/UserInterestController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/UserInterestDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/UserInterestMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/User.java, farketmez/src/main/java/com/mmhb/farketmez/model/UserInterest.java, farketmez/src/main/java/com/mmhb/farketmez/repository/InterestRepository.java, farketmez/src/main/java/com/mmhb/farketmez/repository/UserInterestRepository.java, farketmez/src/main/java/com/mmhb/farketmez/repository/UserTypeRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserInterestService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java, farketmez/src/main/resources/application-dev.properties, farketmez/src/test/java/com/mmhb/farketmez/service/UserInterestServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/UserServiceTest.java
Reverts farketmez-app/farketmez-backend#52
=> Revert "intersttype a bağlı olarak user-interest ksıımları kaldırılarak many to many ilişkisi göz öünde bulunduruldu."

farketmez/src/main/java/com/mmhb/farketmez/controller/UserController.java
Response is like the following now:
```
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huQGRvZS5jb20iLCJpYXQiOjE3MDQ1NjQxNDYsImV4cCI6MTcwNDU2NTA0Nn0.6VGTGY679ynG___wmv8aiyjnzVOQaTmy_e_-4Rbgpbz5u9DsemN2_dDqoQNXC97QhOdOBv9dYgWKs3UnKKl9lw
id: 2
```
(⚠️ has TODO in it)
=> Add userId to login response

farketmez/src/main/java/com/mmhb/farketmez/model/User.java, farketmez/src/main/java/com/mmhb/farketmez/repository/UserTypeRepository.java, farketmez/src/main/java/com/mmhb/farketmez/security/SecurityConfig.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java
user create methodunda usertype bilgisi çekilmediğinden kullanıcı kaydolmuyordu.
şimdilik usertype kısmını sadece user çekecek şekilde düzenleyerek kullanıcının kaydolması sağlandı.
=> Fixed create user method

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/java/com/mmhb/farketmez/util/JwtUtil.java
Etkinlikler için eski ve gelecekte olmak üzere filtrelenmeli.
filtreleme işlemi sağlandı.
=> Eski etkinlikler ve gelecekteki etkinlikler listelendi

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/security/SecurityConfig.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java
Kullanıcı public etkinlik sayfasından etkinliğe katılabilmeli
JoinEvent methodu oluşturuldu burada verilen kullanıcı ID ve etkinlik ID ile ilgili User ve Event nesnelerini bulunup yeni bir Participant nesnesi oluşturdu ve bu nesne veritabanına kaydedildi. Contollerda da gerekli geçiş sağlandı.
=> Etkinliğe katıl işlemi sağlandı

farketmez/src/main/java/com/mmhb/farketmez/controller/ParticipantController.java
Userın katıldığı etkinlikleri döner.
=> Return joined events

farketmez/src/main/java/com/mmhb/farketmez/controller/ParticipantController.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
Participant servisindeki yeni methodlar için test methodları eklenmeliydi
Testler başarıyla geçmiştir.
=> Particiant servis clasına uygun testler eklendi

farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
puan hiç verilmediyse hem null olarak hem de yeni puan olarak iki ayrı veri  ekleniyordu.
Kontrol eklenerek duplicated veri engellendi
=> Puanlama Düzeltildi.

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java
Yakınımdaki etkinliklerin  lat, longları eşit olanlar gruplanması gerekliydi
nearEvents istenen şekilde gruplandırılarak listelendi.
=> Yakınımdaki etkinlikler gruplandırıldı

farketmez/farketmez_db/farketmez_db_script/farketmez_db_02.sql, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/dto/EventDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/EventMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Event.java, farketmez/src/main/java/com/mmhb/farketmez/repository/EventRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/main/java/com/mmhb/farketmez/util/RandomStringUtil.java, farketmez/src/main/resources/application.properties, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java
- Secure link added
- On creating any event, if activity set private, string randomly generates for access_key
- Event table has "access_key" column now. You can update your db with sql script which named "farketmez_db_02.sql"
- Example usage: "http://localhost:8080/events/private/join/1Sa503Ers?id=1"
=> secureLink added

farketmez/src/main/resources/application.properties, farketmez/src/test/java/com/mmhb/farketmez/service/ParticipantServiceTest.java
Event clasının güncllenmesinden sonra participant testlerinde constructor kaynaklı hata oluştu.
Constructor güncellenerek hata düzeltilmiştir.
=> participant testi güncllendi

farketmez/farketmez_db/farketmez_db_script/farketmez_db_04.sql, farketmez/src/main/java/com/mmhb/farketmez/dto/LocationDTO.java, farketmez/src/main/java/com/mmhb/farketmez/mapper/LocationMapper.java, farketmez/src/main/java/com/mmhb/farketmez/model/Location.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java, farketmez/src/test/java/com/mmhb/farketmez/service/EventServiceTest.java, farketmez/src/test/java/com/mmhb/farketmez/service/LocationServiceTest.java
Event için location id girilmeden create işlemi yapılmalı.
Location tablosuna google maps url eklenmeli.
Event locaiton id almadan da oluşturulabilecek şekilde güncllendi.
Locaiton tablosuna sütun eklenerek google maps ürl eklendi ve buna bağlı yerler güncllendi
Testler değişikliklere uygun şekilde güncllendi.
=> Event ve location güncellendi.

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/repository/EventRepository.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java
- Due to the pool option named my-events, the id parameter has been added.
- Example usage of endpoint : 
http://localhost:8080/events/suggestedevent-withparams?place=home&cost=cheap&date=15.01.2024&time=&pool=my-events&id=1
=> suggest event with parameters done

farketmez/farketmez_db/farketmez_db_script/farketmez_db_05.sql, farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/service/ForgotPasswordService.java, farketmez/src/main/java/com/mmhb/farketmez/service/ParticipantService.java, farketmez/src/main/java/com/mmhb/farketmez/service/UserService.java
Etkinliğin ortalama puanını hesaplamak için trigger eklenmeliydi.
Eklenen sql scripti ile artık ortalama puan hesaplanabilmektedir.
=> Etkinliğin ortalama puanını hesaplamak için trigger oluşturuldu

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java
Etkinlik arama özelliği eklenmeliydi.
searchQuery kullanarak etkinlik arama sağlandı.
=> Etkinlik arama özelliği eklendi

farketmez/src/main/java/com/mmhb/farketmez/controller/EventController.java, farketmez/src/main/java/com/mmhb/farketmez/service/EventService.java
Etkinlik mekan, fiyat ve derece gibi parametrelere göre filtrelenmeliydi.
Etkinlik listesi tutulup parametrelere göre filtrelenmesi sağlandı.
=> Etkinlik filtreleme eklendi
